"{{ Abbreviations }}
abbr _SH #!/bin/bash
ab :white_check_mark: ✅
ab :bulb: 💡
ab :smile: ☺
ab :pushpin: 📌
ab :construction: 🚧
ab :point_right: 👉
ab :link: 🔗
ab :wrench: 🔧
ab :email: 📧
ab :computer: 💻
ab :keyboard: ⌨️
ab :whale: 🐋
ab sout System.out.println(
