#!/usr/bin/env bash
display_help() {
    echo "Usage: lorem [# paragraphs]"
    echo "Lorem to display # lines of lorem paragraphs."
    echo "Options:"
    echo "-h, --help    Display this help message."
    echo "-v, --version Display the script version."
    # Add more flag descriptions as needed
}

if [[ $1 == "-h" || $1 == "--help" ]]; then
    display_help    # Call the display_help function
    exit 0          # Exit the script after displaying help
fi

exec curl -sSL "http://metaphorpsum.com/paragraphs/$1"

