#!/bin/bash

# Produces a centered title in the middle of a horizontal rule of text.

_filter(){
  [[ -n "$1" ]] && return 1
  while IFS= read -ra args; do
    "${FUNCNAME[1]}" "${args[@]}"
  done
}

htitle() {
  _filter "$@" && return $?
  local str="$1" char="${2:--}"
  echo "\"{{ "$str" }}"
}

htitle "$@"
