#!/usr/bin/env bash
# This saves text to a file called buf in the saved folder
if [ ! -d ~/.saved ]; then
    mkdir ~/.saved
fi

true > ~/.saved/buf
while IFS= read -r line;do
  echo "$line" >> ~/.saved/buf
  echo "$line"
done


